version: '3.8'

services:
  gin-receiver:
    extends:
      file: ./receiver/docker-compose.yml
      service: gin-app

  go-caller:
    build:
      context: ./caller
      dockerfile: Dockerfile
    ports:
      - "8080:3000"  # mapping container's port 3000 to my 8080

  postgres:
    extends:
      file: ./receiver/docker-compose.yml
      service: postgres

  redis:
    extends:
      file: ./receiver/docker-compose.yml
      service: redis
